### PR TITLE
doc: compiler.

### PR DESCRIPTION
**Pull request by hihiboss**
~resolved: #[issue number]~

details:

Documentation the compiler.

~- [ ] Test case~

### CODE REVIEW

**Comment by joomanzi** [comment]
how about adding assignment operator such as += , -=, ...
i researched other language spec, some has section for assignment operator and some has not.
so i think it depends on our hand. we can count on this

**Comment by hihiboss** [comment]
@joomanzi 
Good idea! But, I think they are not matched to our concept. Our concept is Simple!
However, that is just my personal opinion. I wonder the other's thought. 

Even if it is decided to add those operators, this feature should be implemented in milestone 0.2.0 or 0.3.0 :)
(Because lexer, parser, compiler, vm.. everyone has to add that feature.)

**Comment by joomanzi** [comment]
lexer already got those feature!

**Comment by hihiboss** [comment]
@joomanzi
Oh, really?! Nice work! I'll add that feature later!

**Comment by junbeomlee** [comment]
Nice work!

**Review by junbeomlee — APPROVED** [review]
LGTM

**Pull request merged**
