### PR TITLE
Fix error messages showing line and column

### LINKED ISSUE #133: [parser] Fix returning error format
In parser.go, formats of returning error are different each other.
I mean, some returning error statement is like below,
return fmt.Sprintf("....")
it is not containing "%s" or "%v".

### PR DESCRIPTION
**Pull request by boohyunsik**
resolved: #133 

Fix error messages showing their line and column.

### CODE REVIEW

**Comment by zeroFruit** [comment]
LGTM

**Review by zeroFruit — DISMISSED** [review]

**Review by zeroFruit — COMMENTED** [review]
How about create new error type like `expectError` which contains `line`, `column` field.
```
type expectError struct {
    line int
    column int
}
```

**Comment by junbeomlee** [comment]
How about add new attribute like `line`, `column` field.

```
type parseError struct {
	token Token
	expectedToken Token
	line int
	column int
}

func (e parseError) Error() string {
	return fmt.Sprintf("[line %d, column %d] expected [%s], but got [%s]",
				TokenTypeMap[e.token], TokenTypeMap[e.expectedToken]),					e.Line, e.Column)
}
``` 

Then we do not have to use fmt.Sprintf("[line %d, column %d] expected [%s], but got [%s]",
TokenTypeMap[e.token], TokenTypeMap[e.expectedToken]), every time!!
just return parseError is enough

**Comment by boohyunsik** [comment]
I will do it!

**Review by zeroFruit — APPROVED** [review]

**Pull request merged**
